import { footerAct1, footerAct2 } from '../assets/base';
import {
  bannerTitInfo,
  sticker,
  section1Coupon01,
  section1Coupon02,
  section1Pd01,
  section1Pd02,
  section2PdImg01,
  section2PdImg02,
  section2PdImg03,
  section2PdImg04,
  section3Pd1,
  section3Pd2,
  section3Pd3,
  section3Pd4,
  section3PdImgLarge,
  section4Coupon01,
  section4Coupon02,
  section4Coupon03,
  section4Coupon04,
  section4Pd1,
  section4Pd2,
  section5PdImg0,
  section5PdImg,
  section5Pd1,
  section5Pd2,
  section5Pd3,
  section5Pd4,
  section6DiscountPdImg2x01,
  section6DiscountPdImg2x02,
  section7PdImg0,
  section7PdImg,
  section8BrandPdImg2x01,
  section8BrandPdImg2x02,
  section9Pd1,
  section9Pd2,
  section9Pd3,
  section9Pd4,
} from '../assets/layout';
export const mockPdData = [
  {
    BlockId: 31,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section1Coupon01,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section1Coupon02,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 42,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '源生美學養生甘酒二入',
        productTitle: '養生熱銷組合',
        marketPrice: '380',
        discountPrice: '320',
        imgSrc: section1Pd01,
        imgTitle: '【源生美學】養生甘酒(175ml)2入組',
      },
      {
        id: 1,
        url: '',
        productName: '星巴克巧克力星冰樂',
        productTitle: '人氣冰飲推薦',
        marketPrice: '',
        discountPrice: '150',
        imgSrc: section1Pd02,
        imgTitle: '星巴克大杯巧克力可可碎片星冰樂',
      },
      {
        id: 2,
        url: '',
        productName: '源生美學養生甘酒二入',
        productTitle: '養生熱銷組合',
        marketPrice: '380',
        discountPrice: '320',
        imgSrc: section1Pd01,
        imgTitle: '【源生美學】養生甘酒(175ml)2入組',
      },
      {
        id: 3,
        url: '',
        productName: '星巴克巧克力星冰樂',
        productTitle: '人氣冰飲推薦',
        marketPrice: '',
        discountPrice: '150',
        imgSrc: section1Pd02,
        imgTitle: '星巴克大杯巧克力可可碎片星冰樂',
      },
      {
        id: 4,
        url: '',
        productName: '源生美學養生甘酒二入',
        productTitle: '養生熱銷組合',
        marketPrice: '380',
        discountPrice: '320',
        imgSrc: section1Pd01,
        imgTitle: '【源生美學】養生甘酒(175ml)2入組',
      },
      {
        id: 5,
        url: '',
        productName: '星巴克巧克力星冰樂',
        productTitle: '人氣冰飲推薦',
        marketPrice: '',
        discountPrice: '150',
        imgSrc: section1Pd02,
        imgTitle: '星巴克大杯巧克力可可碎片星冰樂',
      },
      {
        id: 6,
        url: '',
        productName: '源生美學養生甘酒二入',
        productTitle: '養生熱銷組合',
        marketPrice: '380',
        discountPrice: '320',
        imgSrc: section1Pd01,
        imgTitle: '【源生美學】養生甘酒(175ml)2入組',
      },
      {
        id: 7,
        url: '',
        productName: '星巴克巧克力星冰樂',
        productTitle: '人氣冰飲推薦',
        marketPrice: '',
        discountPrice: '150',
        imgSrc: section1Pd02,
        imgTitle: '星巴克大杯巧克力可可碎片星冰樂',
      },
    ],
  },
  {
    BlockId: 53,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'CoCo夏日清涼飲品組',
        productTitle: '夏日買一送一',
        marketPrice: '320',
        discountPrice: '299',
        imgSrc: section2PdImg01,
        imgTitle: 'CoCo 都可 夏日清涼活動',
      },
      {
        id: 1,
        url: '',
        productName: 'ColdStone冰淇淋禮盒',
        productTitle: '送鈣發泡錠',
        marketPrice: '1680',
        discountPrice: '1449',
        imgSrc: section2PdImg02,
        imgTitle: 'Cold Stone 冰淇淋聯名組',
      },
      {
        id: 2,
        url: '',
        productName: 'Hagendazs經典冰淇淋',
        productTitle: '送鈣發泡錠',
        marketPrice: '620',
        discountPrice: '510',
        imgSrc: section2PdImg03,
        imgTitle: 'Häagen-Dazs 冰淇淋',
      },
      {
        id: 3,
        url: '',
        productName: 'Starbucks益生菌組',
        productTitle: '送150P幣好禮',
        marketPrice: '2999',
        discountPrice: '2599',
        imgSrc: section2PdImg04,
        imgTitle: 'Starbucks 聯名益生菌',
      },
      {
        id: 4,
        url: '',
        productName: 'CoCo清涼茶飲組合',
        productTitle: '夏日買一送一',
        marketPrice: '320',
        discountPrice: '299',
        imgSrc: section2PdImg01,
        imgTitle: 'CoCo 都可 夏日清涼活動',
      },
      {
        id: 5,
        url: '',
        productName: 'ColdStone派對冰品組',
        productTitle: '送鈣發泡錠',
        marketPrice: '1680',
        discountPrice: '1449',
        imgSrc: section2PdImg02,
        imgTitle: 'Cold Stone 冰淇淋聯名組',
      },
      {
        id: 6,
        url: '',
        productName: 'Hagendazs人氣冰品',
        productTitle: '送鈣發泡錠',
        marketPrice: '620',
        discountPrice: '510',
        imgSrc: section2PdImg03,
        imgTitle: 'Häagen-Dazs 冰淇淋',
      },
      {
        id: 7,
        url: '',
        productName: 'Starbucks機能保健組',
        productTitle: '送150P幣好禮',
        marketPrice: '2999',
        discountPrice: '2599',
        imgSrc: section2PdImg04,
        imgTitle: 'Starbucks 聯名益生菌',
      },
    ],
  },
  {
    BlockId: 64,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '哈根達斯即享迷你杯冰淇淋',
        productTitle: '即享甜點首選',
        marketPrice: '129',
        discountPrice: '129',
        imgSrc: section3Pd1,
        imgTitle: '哈根達斯 冰淇淋迷你杯',
      },
      {
        id: 1,
        url: '',
        productName: '哈根達斯人氣冰淇淋舒芙蕾',
        productTitle: '人氣內用甜點',
        marketPrice: '424',
        discountPrice: '403',
        imgSrc: section3Pd2,
        imgTitle: '哈根達斯 冰淇淋舒芙蕾',
      },
      {
        id: 2,
        url: '',
        productName: '哈根達斯單球冰淇淋',
        productTitle: '經典口味推薦',
        marketPrice: '145',
        discountPrice: '145',
        imgSrc: section3Pd3,
        imgTitle: '哈根達斯 冰淇淋單球',
      },
      {
        id: 3,
        url: '',
        productName: '麥當勞OREO冰炫風',
        productTitle: '超人氣冰品',
        marketPrice: '',
        discountPrice: '55',
        imgSrc: section3Pd4,
        imgTitle: '麥當勞 OREO 冰炫風',
      },
      {
        id: 4,
        url: '',
        productName: '新市農會頂級毛豆冰淇淋X2盒(90g-6杯/盒)',
        productTitle: '送150P幣+多好禮',
        marketPrice: '',
        discountPrice: '2599',
        imgSrc: section3PdImgLarge,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '哈根達斯人氣冰淇淋舒芙蕾',
        productTitle: '人氣內用甜點',
        marketPrice: '424',
        discountPrice: '403',
        imgSrc: section3Pd2,
        imgTitle: '哈根達斯 冰淇淋舒芙蕾',
      },
      {
        id: 6,
        url: '',
        productName: '哈根達斯即享迷你杯冰淇淋',
        productTitle: '經典口味推薦',
        marketPrice: '145',
        discountPrice: '145',
        imgSrc: section3Pd3,
        imgTitle: '哈根達斯 冰淇淋單球',
      },
      {
        id: 7,
        url: '',
        productName: '麥當勞OREO冰炫風',
        productTitle: '超人氣冰品',
        marketPrice: '',
        discountPrice: '55',
        imgSrc: section3Pd4,
        imgTitle: '麥當勞 OREO 冰炫風',
      },
    ],
  },
  {
    BlockId: 220,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section4Coupon01,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section4Coupon02,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section4Coupon03,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section4Coupon04,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 231,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '冰鎮清爽泡泡果茶/箱購',
        productTitle: '夏日清爽必備',
        marketPrice: '420',
        discountPrice: '350',
        imgSrc: section4Pd1,
        imgTitle: '冰鎮泡泡果茶315ml 12入',
      },
      {
        id: 1,
        url: '',
        productName: '泰山冰鎮水果茶箱',
        productTitle: '暢飲大容量',
        marketPrice: '600',
        discountPrice: '552',
        imgSrc: section4Pd2,
        imgTitle: '泰山 冰鎮水果茶535ml 24入',
      },
      {
        id: 2,
        url: '',
        productName: '冰鎮清爽泡泡果茶/箱購',
        productTitle: '夏日清爽必備',
        marketPrice: '420',
        discountPrice: '350',
        imgSrc: section4Pd1,
        imgTitle: '冰鎮泡泡果茶315ml 12入',
      },
      {
        id: 3,
        url: '',
        productName: '泰山冰鎮水果茶箱',
        productTitle: '暢飲大容量',
        marketPrice: '600',
        discountPrice: '552',
        imgSrc: section4Pd2,
        imgTitle: '泰山 冰鎮水果茶535ml 24入',
      },
      {
        id: 4,
        url: '',
        productName: '冰鎮清爽泡泡果茶/箱購',
        productTitle: '夏日清爽必備',
        marketPrice: '420',
        discountPrice: '350',
        imgSrc: section4Pd1,
        imgTitle: '冰鎮泡泡果茶315ml 12入',
      },
      {
        id: 5,
        url: '',
        productName: '泰山冰鎮水果茶箱',
        productTitle: '暢飲大容量',
        marketPrice: '600',
        discountPrice: '552',
        imgSrc: section4Pd2,
        imgTitle: '泰山 冰鎮水果茶535ml 24入',
      },
      {
        id: 6,
        url: '',
        productName: '冰鎮清爽泡泡果茶/箱購',
        productTitle: '夏日清爽必備',
        marketPrice: '420',
        discountPrice: '350',
        imgSrc: section4Pd1,
        imgTitle: '冰鎮泡泡果茶315ml 12入',
      },
      {
        id: 7,
        url: '',
        productName: '泰山冰鎮水果茶箱',
        productTitle: '暢飲大容量',
        marketPrice: '600',
        discountPrice: '552',
        imgSrc: section4Pd2,
        imgTitle: '泰山 冰鎮水果茶535ml 24入',
      },
      {
        id: 8,
        url: '',
        productName: '冰鎮清爽泡泡果茶/箱購',
        productTitle: '夏日清爽必備',
        marketPrice: '420',
        discountPrice: '350',
        imgSrc: section4Pd1,
        imgTitle: '冰鎮泡泡果茶315ml 12入',
      },
      {
        id: 9,
        url: '',
        productName: '泰山冰鎮水果茶箱',
        productTitle: '暢飲大容量',
        marketPrice: '600',
        discountPrice: '552',
        imgSrc: section4Pd2,
        imgTitle: '泰山 冰鎮水果茶535ml 24入',
      },
      {
        id: 10,
        url: '',
        productName: '冰鎮清爽泡泡果茶/箱購',
        productTitle: '夏日清爽必備',
        marketPrice: '420',
        discountPrice: '350',
        imgSrc: section4Pd1,
        imgTitle: '冰鎮泡泡果茶315ml 12入',
      },
      {
        id: 11,
        url: '',
        productName: '泰山冰鎮水果茶箱',
        productTitle: '暢飲大容量',
        marketPrice: '600',
        discountPrice: '552',
        imgSrc: section4Pd2,
        imgTitle: '泰山 冰鎮水果茶535ml 24入',
      },
    ],
  },
  {
    BlockId: 242,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '芒果狂歡能量碳酸飲料易開罐',
        productTitle: '清涼一夏買一送一',
        marketPrice: '',
        discountPrice: '2999',
        imgSrc: section5PdImg0,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '魔爪蜜桃風味無糖能量飲',
        productTitle: '清爽無糖提神',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd1,
        imgTitle: 'Monster 魔爪 蜜桃能量飲',
      },
      {
        id: 2,
        url: '',
        productName: '魔爪超越系列經典能量飲',
        productTitle: '經典提神首選',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd2,
        imgTitle: 'Monster 魔爪 超越能量飲',
      },
      {
        id: 3,
        url: '',
        productName: '魔爪潘趣果香碳酸能量飲',
        productTitle: '果香能量補給',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd3,
        imgTitle: 'Monster 魔爪 管浪潘趣',
      },
      {
        id: 4,
        url: '',
        productName: '魔爪仙境風味無糖能量飲',
        productTitle: '無糖暢飲推薦',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd4,
        imgTitle: 'Monster 魔爪 仙境能量飲',
      },
      {
        id: 5,
        url: '',
        productName: '魔爪蜜桃風味無糖能量飲',
        productTitle: '清爽無糖提神',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd1,
        imgTitle: 'Monster 魔爪 蜜桃能量飲',
      },
      {
        id: 6,
        url: '',
        productName: '魔爪超越系列經典能量飲',
        productTitle: '經典提神首選',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd2,
        imgTitle: 'Monster 魔爪 超越能量飲',
      },
      {
        id: 7,
        url: '',
        productName: '魔爪潘趣果香碳酸能量飲',
        productTitle: '果香能量補給',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd3,
        imgTitle: 'Monster 魔爪 管浪潘趣',
      },
      {
        id: 8,
        url: '',
        productName: '魔爪仙境風味無糖能量飲',
        productTitle: '無糖暢飲推薦',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd4,
        imgTitle: 'Monster 魔爪 仙境能量飲',
      },
      {
        id: 9,
        url: '',
        productName: '魔爪蜜桃風味無糖能量飲',
        productTitle: '清爽無糖提神',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd1,
        imgTitle: 'Monster 魔爪 蜜桃能量飲',
      },
      {
        id: 10,
        url: '',
        productName: '魔爪超越系列經典能量飲',
        productTitle: '經典提神首選',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd2,
        imgTitle: 'Monster 魔爪 超越能量飲',
      },
      {
        id: 11,
        url: '',
        productName: '魔爪潘趣果香碳酸能量飲',
        productTitle: '果香能量補給',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd3,
        imgTitle: 'Monster 魔爪 管浪潘趣',
      },
      {
        id: 12,
        url: '',
        productName: '魔爪仙境風味無糖能量飲',
        productTitle: '無糖暢飲推薦',
        marketPrice: '1416',
        discountPrice: '1111',
        imgSrc: section5Pd4,
        imgTitle: 'Monster 魔爪 仙境能量飲',
      },
    ],
  },
  {
    BlockId: 88,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x01,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x02,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x01,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x02,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x01,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x02,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x01,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section6DiscountPdImg2x02,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 99,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '一次性隱形眼鏡盒性隱形眼鏡盒',
        productTitle: '星巴克清涼一夏買一送',
        marketPrice: '',
        discountPrice: 2999,
        imgSrc: section5PdImg,
        imgTitle: '一次性隱形眼鏡盒性隱形眼鏡盒',
      },
      {
        id: 1,
        url: '',
        productName: '好立善 維他命C發泡錠x12+維他命C口含錠',
        productTitle: '送鈣發泡錠',
        marketPrice: '',
        discountPrice: 1449,
        imgSrc: section5PdImg,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '一次性隱形眼鏡盒性隱形眼鏡盒',
        productTitle: '星巴克清涼一夏買一送',
        marketPrice: '',
        discountPrice: 2999,
        imgSrc: section5PdImg,
        imgTitle: '一次性隱形眼鏡盒性隱形眼鏡盒',
      },
      {
        id: 3,
        url: '',
        productName: '好立善 維他命C發泡錠x12+維他命C口含錠',
        productTitle: '送鈣發泡錠',
        marketPrice: '',
        discountPrice: 1449,
        imgSrc: section5PdImg,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '一次性隱形眼鏡盒性隱形眼鏡盒',
        productTitle: '星巴克清涼一夏買一送',
        marketPrice: '',
        discountPrice: 2999,
        imgSrc: section5PdImg,
        imgTitle: '一次性隱形眼鏡盒性隱形眼鏡盒',
      },
      {
        id: 5,
        url: '',
        productName: '好立善 維他命C發泡錠x12+維他命C口含錠',
        productTitle: '送鈣發泡錠',
        marketPrice: '',
        discountPrice: 1449,
        imgSrc: section5PdImg,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '一次性隱形眼鏡盒性隱形眼鏡盒',
        productTitle: '星巴克清涼一夏買一送',
        marketPrice: '',
        discountPrice: 2999,
        imgSrc: section5PdImg,
        imgTitle: '一次性隱形眼鏡盒性隱形眼鏡盒',
      },
      {
        id: 7,
        url: '',
        productName: '好立善 維他命C發泡錠x12+維他命C口含錠',
        productTitle: '送鈣發泡錠',
        marketPrice: '',
        discountPrice: 1449,
        imgSrc: section5PdImg,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 110,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '哈根達斯3.5吋冰淇淋蛋糕商品禮券',
        productTitle: '甜蜜蛋糕禮券',
        marketPrice: '1380',
        discountPrice: '1318',
        imgSrc: section7PdImg0,
        imgTitle: '【Häagen-Dazs哈根達斯】3.5吋冰淇淋蛋糕商品禮券(1入)',
      },
      {
        id: 1,
        url: '',
        productName: '哈根達斯人氣冰淇淋舒芙蕾',
        productTitle: '人氣內用甜點',
        marketPrice: '424',
        discountPrice: '403',
        imgSrc: section3Pd2,
        imgTitle: '哈根達斯 冰淇淋舒芙蕾',
      },
      {
        id: 2,
        url: '',
        productName: '哈根達斯單球冰淇淋',
        productTitle: '經典口味推薦',
        marketPrice: '145',
        discountPrice: '145',
        imgSrc: section3Pd3,
        imgTitle: '哈根達斯 冰淇淋單球',
      },
      {
        id: 3,
        url: '',
        productName: '麥當勞OREO冰炫風',
        productTitle: '超人氣冰品',
        marketPrice: '',
        discountPrice: '55',
        imgSrc: section3Pd4,
        imgTitle: '麥當勞 OREO 冰炫風',
      },
      {
        id: 4,
        url: '',
        productName: '新市農會頂級毛豆冰淇淋X2盒(90g-6杯/盒)',
        productTitle: '送150P幣+多好禮',
        marketPrice: '',
        discountPrice: '2599',
        imgSrc: section3PdImgLarge,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '哈根達斯人氣冰淇淋舒芙蕾',
        productTitle: '人氣內用甜點',
        marketPrice: '424',
        discountPrice: '403',
        imgSrc: section3Pd2,
        imgTitle: '哈根達斯 冰淇淋舒芙蕾',
      },
      {
        id: 6,
        url: '',
        productName: '哈根達斯即享迷你杯冰淇淋',
        productTitle: '經典口味推薦',
        marketPrice: '145',
        discountPrice: '145',
        imgSrc: section3Pd3,
        imgTitle: '哈根達斯 冰淇淋單球',
      },
      {
        id: 7,
        url: '',
        productName: '麥當勞OREO冰炫風',
        productTitle: '超人氣冰品',
        marketPrice: '',
        discountPrice: '55',
        imgSrc: section3Pd4,
        imgTitle: '麥當勞 OREO 冰炫風',
      },
    ],
  },
  {
    BlockId: 121,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x01,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x02,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x01,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x02,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x01,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x02,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x01,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '折價券',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: section8BrandPdImg2x02,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 289,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '巴伐亞零酒精生啤風味飲',
        productTitle: '清爽零負擔',
        marketPrice: '1800',
        discountPrice: '1640',
        imgSrc: section9Pd1,
        imgTitle: 'Bavaria 零酒精生啤風味飲',
      },
      {
        id: 1,
        url: '',
        productName: '巴伐亞草莓風味零酒精蘇打',
        productTitle: '甜心果香推薦',
        marketPrice: '1800',
        discountPrice: '1640',
        imgSrc: section9Pd2,
        imgTitle: 'Bavaria 草莓風味零酒精蘇打',
      },
      {
        id: 2,
        url: '',
        productName: '北歐櫥窗紀念精釀啤酒杯',
        productTitle: '收藏質感首選',
        marketPrice: '1300',
        discountPrice: '1170',
        imgSrc: section9Pd3,
        imgTitle: 'Holmegaard x Mikkeller 紀念啤酒杯',
      },
      {
        id: 3,
        url: '',
        productName: 'Royal黑麥風味零酒精飲',
        productTitle: '濃厚麥香風味',
        marketPrice: '1450',
        discountPrice: '988',
        imgSrc: section9Pd4,
        imgTitle: 'Royal 黑麥風味零酒精飲',
      },
      {
        id: 4,
        url: '',
        productName: '北歐櫥窗紀念精釀啤酒杯',
        productTitle: '收藏質感首選',
        marketPrice: '1300',
        discountPrice: '1170',
        imgSrc: section9Pd3,
        imgTitle: 'Holmegaard x Mikkeller 紀念啤酒杯',
      },
      {
        id: 5,
        url: '',
        productName: 'Royal黑麥風味零酒精飲',
        productTitle: '濃厚麥香風味',
        marketPrice: '1450',
        discountPrice: '988',
        imgSrc: section9Pd4,
        imgTitle: 'Royal 黑麥風味零酒精飲',
      },
      {
        id: 6,
        url: '',
        productName: '北歐櫥窗紀念精釀啤酒杯',
        productTitle: '收藏質感首選',
        marketPrice: '1300',
        discountPrice: '1170',
        imgSrc: section9Pd3,
        imgTitle: 'Holmegaard x Mikkeller 紀念啤酒杯',
      },
      {
        id: 7,
        url: '',
        productName: 'Royal黑麥風味零酒精飲',
        productTitle: '濃厚麥香風味',
        marketPrice: '1450',
        discountPrice: '988',
        imgSrc: section9Pd4,
        imgTitle: 'Royal 黑麥風味零酒精飲',
      },
    ],
  },
  {
    BlockId: 816,
    Nodes: [
      {
        id: 2,
        url: '',
        productName: '天天簽到',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '限時瘋搶',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct2,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 827,
    Nodes: [
      {
        id: 2,
        url: '',
        productName: '活動總覽',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: sticker,
        imgTitle: '',
      },
    ],
  },
];
